- name: Initialize k8s_install master
  become: true
  shell: kubeadm init --apiserver-advertise-address={{ k8s_master_ip }} --pod-network-cidr={{ k8s_pod_cidr }} --node-name k8s-master --apiserver-cert-extra-sans={{ ansible_host }}
- name: "Setup kubeconfig for {{ user }} user"
  command: "{{ item }}"
  with_items:
    - "mkdir -p /home/{{ user }}/.kube"
    - "cp -i /etc/kubernetes/admin.conf /home/{{ user }}/.kube/config"
    - "chown {{ user }}:{{ user }} /home/{{ user }}/.kube/config"

- name: Install calico pod network
  become: false
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml #https://docs.projectcalico.org/v3.9/manifests/calico.yaml

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  become: false
  local_action:
    module: copy
    content: "{{ join_command.stdout_lines[0] }}"
    dest: "./join-command.sh"